version: '3.1'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce
    ports:
      - 3307:3306
    restart: always
 
  app:
    image: ecommerce:latest
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce?createDatabaseIfNotExist=true
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
       - 8081:8080
    depends_on:
       - db
       - redis
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    